### ISSUE TITLE
card异常

### ISSUE THREAD

**Issue by jizizr** [unknown-o/loveway-php#1]
![image](https://user-images.githubusercontent.com/78908842/119769703-7dadc980-beed-11eb-8147-3d6e2474b9f3.png)

**Comment by unknown-o** [comment]
已经修复了

**Comment by jizizr** [comment]
![image](https://user-images.githubusercontent.com/78908842/121285919-b26c4880-c911-11eb-93dd-34d816c48cab.png)
背景未铺满

**Comment by unknown-o** [comment]
> ![image](https://user-images.githubusercontent.com/78908842/121285919-b26c4880-c911-11eb-93dd-34d816c48cab.png)
> 背景未铺满

请更新最新版（1.3.2版本）。另外如果遇到问题请新建一个issue，不要在老的issue下回复，，
