### ISSUE TITLE
新增图片上传功能

### ISSUE THREAD

**Issue by saltedfisholdxu** [unknown-o/loveway-php#2]
根据测试和多为同学反映，您的程序的图片可以修改成选取图片上传的方式吗？填写http协议的图床的方式对于一些萌新来说很不友好

**Comment by unknown-o** [comment]
你好，我们已经收到多次类似的建议了。我们可能会考虑做成一个可开关的功能。毕竟此功能写不好可能导致安全风险。
至于什么时候上线此功能，可能被我排到国庆以后了，因为最近有点忙，没什么时间维护开源项目

**Comment by saltedfisholdxu** [comment]
我的想法是：因为你POST过去是HTTP链接，那么就可以另外使用一个上传图片的form（需要勾选是否添加图片）之后进行上传（希望可以是多个图片）

**Comment by unknown-o** [comment]
首先，本表白墙是不会支持多张图片上传的。并且我会把图片上传功能作为一项功能，可以通过config.php开关。另外最近有点忙，根本没时间维护开源项目。希望能按照计划在国庆的时候发布新版本。
另外，如果你需要这些功能，你也可以选择自己开发。开发完成后可以给本项目提Pull Requests，本人非常欢迎各路大神帮忙维护本项目。当然你也可以不提Pull Requests，但是你要遵循本项目的开源协议
