### ISSUE TITLE
图片上传建议

### ISSUE THREAD

**Issue by Dnyo666** [unknown-o/loveway-php#4]
可不可以添加七牛云或者其他的云存储，也可以设置上传文件的大小（如果在php那里改的话，其他地方又会受影响）
也可以做一个自带随机图片api的功能，虽然但是部分人会api，但是如果加上的话，也许会增加功能性和便利性
麻烦作者了

**Comment by unknown-o** [comment]
1.目前暂时不支持七牛云等其他云存储，建议将七牛云挂载到网站目录
2.您可以在config.php中修改上传文件的大小

**Comment by Dnyo666** [comment]
好的，谢谢了
