### ISSUE TITLE
使用最新版本(v1.5.9)时遇到的部分问题记录

### ISSUE THREAD

**Issue by Lavoltz** [unknown-o/loveway-php#6]
后续整理一下我的改动，可能会交个pr吧
### Bug/问题部分：
- [x] 1.分享功能依赖正确的服务器名称，使用虚拟主机时可能无法获取正确链接
解决方法：将SERVER_NAME替换成HTTP_HOST
- [x] 2.后台自定义文本内容部分HTML内容没有转义，保存包含双引号的HTML内容会导致下一次打开管理员面板时出现鬼畜的结果，且可能无法正确保存
解决方法：对这部分内容转义
- [ ] **3.表白，配图和评论提交应该都没有对XSS漏洞作出处理**，未确认是否存在SQL注入漏洞，但存在可能。**
解决方法：嫌麻烦的话就开WAF吧……改这个应该是个大工程
- [x] 4.表白时如果没有完整填写必填项就提交，会导致无法获取卡片ID而跳转到card/undefined，然后跳转到404页面，导致编辑内容全部丢失，搞人心态。
解决方法：提交前在前端验证数据有效性，后端出错时识别并阻止页面跳转。
- [ ] 5.进行操作后的刷新似乎不太及时，不过可能是我设备不好吧。
- [ ] 6.部分API好像挂了？llilii.cn
### 优化部分（个人认为）：
- [ ] 1.允许管理员单独删除某条评论
- [ ] 2.读取QQ头像很天才，但是或许应该允许留空然后展示<del>镜音铃</del>（后台设置的或者写死的）默认图像，表白者昵称同上。
- [ ] 3.或许可以允许用户少填一些信息，如一句话描述，并在上述情况下适应布局（如使表白对象的元素上下居中）
- [ ] 4.自定义页面可以允许隐藏，或者至少允许修改副标题
- [ ] 5.减少写死的文本，如果没时间写管理面板也可以直接放数据库/配置文件里（改数据库/配置文件毕竟比改代码方便，不过可能会降低运行效率），如果实在没时间就算了。
- [ ] 6.向用户提供一种标记管理员发布的可信内容的方式，目前只能通过修改时间为9999年达到置顶的效果，不过可信内容并不总是置顶……
- [ ] 7.赞/评论的数字和图标好像没对齐，不过这是小问题。

以上内容是本人在使用过程中遇到的问题和想法，供后面的使用者参考。优化部分并不是刚需内容。

**Comment by unknown-o** [comment]
感谢您提交的建议，期待你的PR
